### ISSUE TITLE
Calls "modules" an error in manifest.json

### ISSUE THREAD

**Issue by Inshomothal** [Blockception/BC-Minecraft-Bedrock-Diagnoser#125]
I copied the manifest of the cotta project tutorial on the [minecraft learn website](https://learn.microsoft.com/en-us/minecraft/creator/documents/scriptinggettingstarted#build-your-arena-with-some-helper-code). After saving the project as a workspace with Visual Studio Code, I received an error in the manifest.json stating the manifest is required for the following data module, javascript.

It doesn't seem like an error and doesn't have a fix if it is.

**To Reproduce**
1. Go to [Build a gameplay experience with TypeScript](https://learn.microsoft.com/en-us/minecraft/creator/documents/scriptinggettingstarted#build-your-arena-with-some-helper-code)
2. Click on https://github.com/microsoft/minecraft-scripting-samples/
3. Follow the steps for setting up the environment
4. Follow the steps till you get to [Build your arena with some helper code](https://learn.microsoft.com/en-us/minecraft/creator/documents/scriptinggettingstarted#build-your-arena-with-some-helper-code)
5. Save the project as a workspace.
6. Notice the errors in the manifest.json file

**Expected behavior**
The manifest.json file will notice 4 errors and one will be the "modules" section.

**Screenshots**
![image](https://user-images.githubusercontent.com/58829269/208065827-59c3d7d7-5434-4feb-8245-3cfb731790c7.png)

Desktop 
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version 108.0.1462.46 (Official build) (64-bit)

**Comment by DaanV2** [comment]
Fixed
