### ISSUE TITLE
Player animations are considered unused

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Diagnoser#178]
![image](https://github.com/Blockception/BC-Minecraft-Bedrock-Diagnoser/assets/72647213/28ebc9c6-49a3-46a5-9810-a29d450c2b62)
Most of these are referenced in the player AC but are still considered unused

**Comment by Xterionix** [comment]
Anything I can do to help move this along?

**Comment by DaanV2** [comment]
No, I just need to test and check this. but haven't had the time yet

**Comment by Xterionix** [comment]
Any news on this?

**Comment by Xterionix** [comment]
Thanks for fixing this!

**Comment by Xterionix** [comment]
I don't think is fixed. I've 7.0.46 of the extension and it's still displaying this error and all the related errors that were meant to be fixed what that commit

**Comment by DaanV2** [comment]
Seeing some errors left, but looking at those manually, those seem really not being used, it a whole lot less 🤔

**Comment by DaanV2** [comment]
If you got an example you can always create an issue :)

**Comment by Xterionix** [comment]
I've got a few less errors than before, but yeah, I'll open an issue
