### ISSUE TITLE
Block Culling Rules

### ISSUE THREAD

**Issue by DaanV2** [Blockception/BC-Minecraft-Bedrock-Diagnoser#179]
- Does it target an existing block?
- Checkout anything we can suggest / improve

Schemas: https://github.com/Blockception/Minecraft-bedrock-json-schemas/issues/231

**Comment by Xterionix** [comment]
I'd say for this, the geometry component can check if it's a valid rule's id and maybe check if the geometry_part points to the right bone/cube? Though that second one might be too hard to check

**Comment by DaanV2** [comment]
Its possible, 🤔 The diagnoser uses mostly summarized information about things in the BP and RP

So first we would have to add the names of bones to the model object 🤔 

The object to be modified: https://github.com/Blockception/BC-Minecraft-Bedrock-Project/blob/main/src/Lib/Project/ResourcePack/Model/Model.ts

And then in processing add the bone names : https://github.com/Blockception/BC-Minecraft-Bedrock-Project/blob/main/src/Lib/Project/ResourcePack/Model/Process.ts

**Comment by DaanV2** [comment]
depend on: https://github.com/Blockception/BC-Minecraft-Bedrock-Project/issues/121
