### ISSUE TITLE
Trident rpac's animations are considered unused

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Diagnoser#181]
![image](https://github.com/Blockception/BC-Minecraft-Bedrock-Diagnoser/assets/72647213/fee5d6fe-b651-4853-9337-57c9e993400a)

**Comment by DaanV2** [comment]
Seems indeed the animations are used by the controller, but somehow the diagnosed isn't seeing this, either that or the wrong information is collected in bedrock-project 🤔

**Comment by Xterionix** [comment]
And this too!
