### ISSUE TITLE
Check if material instance points to valid texture in terrain textures

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Diagnoser#208]

**Comment by Xterionix** [comment]
Looked into this; keys from `diagnoser.getCache().textures` do include textures found from atlas files. Although, I'm not sure there's a way to differentiate between whether it was an atlas texture, and if it came from `terrain_texture.json` rather than `item_texture.json`. Any ideas on what I should do?

**Comment by DaanV2** [comment]
Would it help if you used this data?

https://github.com/Blockception/BC-Minecraft-Bedrock-Vanilla-Data/blob/main/src/Lib/Vanilla/ResourcePack/sounds_files.ts

**Comment by Xterionix** [comment]
That's just hardcoded vanilla sound paths, the material instance can point to a custom texture.

**Comment by DaanV2** [comment]
All found texture atlasses end up atleast in diagnoser.getCache().resourcespack.textures.

Do no vanilla atlast is defined yet 🤔 , probably need to add those to the vanilla collection, and then create a function in the diagnosed to see if its an existing ID or not

**Comment by DaanV2** [comment]
It should

**Comment by Xterionix** [comment]
Alr. I'll look into this when I get the chance and resolve this and #165
