### ISSUE TITLE
Floats are completely lost after Json.LoadReport<>()

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Diagnoser#267]
```json
"paeaefae:aeae": {
    "type": "float",
    "default": 3.2,
    "range": [ 0.0, 2.0 ]
}
```

When read by the diagnoser, the default value for this actor property is 3. Just logging `jsonc.prase(diagnoser.document)` contains the 3.2 value.

Most likely happens in other places too, but this is where I noticed it

**Comment by Xterionix** [comment]
@DaanV2 Thoughts?

**Comment by DaanV2** [comment]
I mean if its wrong, it should be updated. Im unsure what you want to gauge 🤔

**Comment by Xterionix** [comment]
I was hoping you'd have an idea on how it can be fixed. Since it seems like the type cast is where the data is lost

**Comment by DaanV2** [comment]
Looked into it, but nothing is turning it to 3, where are you finding this?

**Comment by DaanV2** [comment]
I ran it with the latest extension, and the only error I'm getting is:

```
Default value is not within the range: 3.2
```

**Comment by Xterionix** [comment]
That's odd, it must be something with my system's environment then. Either way this isn't an issue then and the pr can be merged
