### ISSUE TITLE
Same texture key in both texture atlases leads to neither one being recognized when used a the block.json or item.json

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Diagnoser#290]
If item_texture.json and terrain_texture.json both have textures references with the same key then only one of them is being saved into the cache leading to both uses flagging errors like "Texture reference "something" was not defined in (item or terrain)_texture.json"

```
{
	"resource_pack_name": "rp",
	"texture_name": "atlas.items",
	"texture_data": {
		"a": {
			"textures": "textures/a"
		}
	}
}
```

```
{
	"resource_pack_name": "rp",
	"texture_name": "atlas.terrain",
	"padding": 8,
	"num_mip_levels": 4,
	"texture_data": {
		"a": {
			"textures": "textures/a"
		}
	}
}
```
Related to #286

**Comment by Xterionix** [comment]
Saving `terrain_texture.json` fixes the error in the `block.json` but brings back the error in the `item.json` and vice versa

**Comment by Xterionix** [comment]
It might be the fact they both point to the same texture path and also have the same key so only one of them gets stored

**Comment by Xterionix** [comment]
Okay, yeah, I believe it's an issue with the ids being the same.

`return this.textures.set(Texture.ProcessTextureAtlas(doc));` calls this._data.set(i.id, i)

**Comment by DaanV2** [comment]
Yeah, probally what needs to happen, it will break alot. but it needs to happen :)

**Comment by Xterionix** [comment]
Would you be able to list what stuff uses it? I'd like to avoid breaking too many things at once

**Comment by DaanV2** [comment]
I wouldnt worry about that, This is a good startup mentality for this problem: Break things, move fast

There is a whole bunch in the diagnoser and the vscode plugins for semantics, completion etc that depends on this. Its going to happen and we just going to need to grit our teeth and solve it :)

Just make the change and then we will see what it truly impacts 😉

**Comment by Xterionix** [comment]
Looked into the extension, didn't see any uses where it would need to be swapped so I think this should be good to go

**Comment by DaanV2** [comment]
Go for it!

**Comment by Xterionix** [comment]
This has been resolved of my earlier pr to the diagnoser repo
