### ISSUE TITLE
use of "deop" with Selectors outputs "Problem" bug?

### ISSUE THREAD

**Issue by LegionX-Code** [Blockception/BC-Minecraft-Bedrock-Diagnoser#93]
**"deop" with "Selectors" is an unknown command in .mcfunction**

"Blockception's Minecraft Bedrock Development - v3.2.105"

**To Reproduce**
1. Open 'VS' with `Blockception Extention' enabled.
2. Create blank Folder.
3. Create new BP `Ctrl + Shift + P`
4. Create a blank: 'foo.mcfunction' in a BP (in VS with Blockception Extention 😄).
5. Open termal: ```Ctrl + Shift + M ```
6. Type (copy/paste) the following into foo.mcfunction :
``` 
## This outputs "NO problem" (Expected behaviour)
op @p
deop @p

## This throws Problem/Error only on "deop", once a Selector is added.
execute @p ~ ~ ~ op @p
execute @p ~ ~ ~ deop @p

## This throws Problem/Error only on "deop"
execute @a[tag=Foo] ~ ~ ~ op @a
execute @a[tag=Foo] ~ ~ ~ deop @a
## ^^ this is where the Problem/Error is suggesting but it appears to be caused by the "deop"
## Change "deop" to op and error/problem goes away
## The link to the Problem/Error is also broken "Page not found" but non issue if this bug didn't exist.
````

7. Save: "foo.mcfunction" (Ctrl + S)
8. See problem/error & red unline 

**Expected behavior**
The same desired outcome as "op".

**Screenshots**
[deop example problem on Imgur](https://imgur.com/a/6b0sZa4)

**Desktop:**
 - OS: WIN 11 Pro - Evaluation copy. Build 225936.ni_release.220402-1100
 
 *Visual Studio:*
 - Version: 1.66.1 (user setup)
 - Electron: 17.2.0
 - Chromium: 98.0.4758.109
 - Node.js: 16.13.0
 - V8: 9.8.177.11-electron.0
 - OS: Windows_NT x64 10.0.22593

**Additional context**

This is the error being thrown:
Unknown command syntax: "execute" mc(mcfunction.sysntax.unknown) links to here:
<https://github.com/Blockception/Minecraft-Error-Codes/blob/main/mcfunction/syntax/unknown.md>
Link is "Page Not Found"

**Comment by DaanV2** [comment]
deop was not included in the command list, its has now been added and upgraded, link has been fixed! 😄
